name: huils
favicon: null
layout_spectrum: 0.64124
typography_spectrum: 0.5618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#b8b8b8'
    - '#617c97'
    - '#885333'
    - '#e3dfd4'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9024337355513126
  rhythmicContrast: 0.5
purpose: []
