name: huils
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eadfcd'
    - '#090913'
    - '#81442f'
    - '#bd8479'
    - '#a5a6e6'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
