name: huils
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5618
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#4b4853'
    - '#6e6c79'
    - '#cab4a7'
    - '#aa8f85'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
