name: huils
favicon: null
layout_spectrum: 0.5258051047567278
typography_spectrum: 0.18432578700594604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.05993089661933482
  lightness: 0.9926741432864219
  saturation: 0.9024337355513126
  rhythmicContrast: 0.19823504355736077
purpose: []
